"""image null false

Revision ID: decd1cc8091b
Revises: f7c0669e8419
Create Date: 2023-09-17 15:43:07.574283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decd1cc8091b'
down_revision = 'f7c0669e8419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'defaultuser.png'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'defaultuser.png'::character varying"))

    # ### end Alembic commands ###
