"""adding image to book

Revision ID: f2abe705427c
Revises: decd1cc8091b
Create Date: 2023-10-23 21:38:17.967929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2abe705427c'
down_revision = 'decd1cc8091b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageSrc', sa.String(length=600), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('imageSrc')

    # ### end Alembic commands ###
